- name: Install nvim
  community.general.homebrew:
    name: neovim
    state: present
  tags:
    - dotfiles
    - install
    - vim
    - ide

- name: Install Packer 
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim    
    accept_hostkey: yes
    force: yes
  tags:
    - dotfiles
    - install
    - vim
    - ide

- name: Use nvim as vim
  shell: |
    if [[ ! -f /usr/local/bin/vim ]]; then
      ln -s /usr/local/bin/nvim /usr/local/bin/vim
    fi
  tags:
    - dotfiles
    - install
    - vim
    - ide

- name: Install Packer dependecies
  shell: vim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
  tags:
    - dotfiles
    - install
    - vim
    - ide

- name: Install eslint_d
  shell: npm install -g eslint_d
  tags:
    - dotfiles
    - install
    - vim
    - eslint
    - nodejs
