---
- name: Install zsh
  community.general.homebrew:
    name: zsh
    state: present

- name: Install wezterm
  community.general.homebrew_cask:
    name: wezterm
    state: present
  tags:
    - install
    - terminal
    - shell
    - prompt
    - tool

- name: Install starship
  community.general.homebrew:
    name: starship
    state: present
  tags:
    - install
    - terminal
    - shell
    - prompt
    - tool

- name: Install oh-my-zsh
  shell: |
    if [[ ! -d ~/.oh-my-zsh ]]; then
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    fi
  tags:
    - install
    - terminal
    - zsh
    - tool

- name: Install antigen
  shell: |
    if [[ ! -f ~/.oh-my-zsh/antigen.zsh ]]; then
      curl -L git.io/antigen > ~/.oh-my-zsh/antigen.zsh
    fi
  tags:
    - install
    - terminal
    - zsh
    - tool
    - plugin-manager

- name: Install zoxide
  community.general.homebrew:
    name: zoxide
    state: present
  tags:
    - install
    - terminal
    - zoxiode
    - directory-navigation
    - vim
    - tool

- name: Install zellij
  community.general.homebrew:
    name: zellij
    state: absent
  tags:
    - not-used-anymore
    - zellij
    - terminal
    - install
    - terminal-multiplexer

- name: Install tmux plugin manager
  ansible.builtin.git:
    repo: git@github.com:tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
    accept_hostkey: yes
    force: yes
  tags:
    - tpm
    - tmux
    - terminal
    - install

- name: Install meslo lg nerd font
  community.general.homebrew_cask:
    name: font-meslo-lg-nerd-font
    state: present
  tags:
    - meslo-lg
    - nerd-font
    - font
    - terminal
    - install
